workspace = { members = ["is-tree-macro"] }
[package]
name = "is-tree"
version = "0.2.0"
edition = "2021"
description = "Everything is a tree"
license = "Apache-2.0"
documentation = "https://docs.rs/is-tree"
homepage = "https://github.com/sensorial-systems/is-tree"
repository = "https://github.com/sensorial-systems/is-tree"

[dependencies]
enum-as-inner = "0.6.0"
is-tree-macro = "0.1.0"
